config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :shippings
  resources :payments
  resources :products
  resources :offers
  resources :brands
  resources :categories
  resources :addresses
  resources :admins
  resources :customers
  resources :orders do
  resources:orderitems
  end

  #resources :orders


  #security measures for app - permissions for different users
  devise_for :admin do
    resources:orders.all
  end

  #admin rule
  get '/makeadmin/:id' => 'static_pages#makeadmin'
  get '/removeadmin/:id' => 'static_pages#removeadmin'

  devise_for :users do
    resources:orders
  end

  #get '/login' => 'user#login'
  #get '/logout' => 'user#logout'
  #get '/register' => 'user#register'

  root 'static_pages#home'

  get '/items' => 'items#index'
  get '/products' => 'products#index'

  #cart section
  get '/checkout' => 'cart#createOrder'
  get 'cart/index'
  get '/cart' => 'cart#index'
  #get 'cart/index'
  get '/cart/:id' => 'cart#add'
  get '/clearcart' => 'cart#clearcart'
  get '/remove/:id' => 'cart#remove'
  get '/decrease/:id' => 'cart#decrease'
  get '/increase/:id' => 'cart#increase'
  get '/paid/:id' => 'static_pages#paid'
  get '/done' => 'cart#done'

  get '/admin' => 'static_pages#admincontrol'

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/shippings' => 'static_pages#shippings'
  get '/support' => 'static_pages#support'
  get '/returns' => 'static_pages#returns'
  get '/offers' => 'static_pages#offers'
  get '/payments' => 'static_pages#payments'
  get '/brands' => 'static_pages#brands'
  get '/addresses' => 'static_pages#addresses'
  get '/customers' => 'static_pages#customers'

  get '/men' => 'static_pages#men'
  #get '/item/:title' => 'static_pages#items'

  get '/women' => 'static_pages#women'

  get '/kids' => 'static_pages#kids'

  #get '/search' => 'search_pages#search'
  #get '/categories' => 'static_pages#categories'
  #get '/category/:title' => 'static_pages#category'

  get '/category' => 'static_pages#category'
  get '/category/:cat_name' => 'static_pages#category'

  post '/search' => 'items#search'
  get '/search' => 'static_pages#search'
  get '/search/:title' => 'static_pages#search'

  get '/shoes' => 'static_pages#shoes'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :payment
  belongs_to :shipping
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord

    validates_presence_of :title, :message => 'Please Enter a Title'
    validates :title, length: {minimum: 5}

    validates_presence_of :description, :message => 'Please Enter a Description'
    validates :description, length: {minimum: 10}

    validates_presence_of :price, :message => 'Please a Price'
    validates :price, length: {minimum: 2}

    validates_presence_of :category, :message => 'Please Enter a Category'
    validates :category, length: {minimum: 3}

    validates_presence_of :brand, :message => 'Please Enter a Brand'
    validates :brand, length: {minimum: 3}

end

# :price, :image_url, :category, :brand

app/models/offer.rb
class Offer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitems
  belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :shipping
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord


    validates_presence_of :prod_name, :message => 'Please Enter a product name'
    validates :prod_name, length: {minimum: 5}

    validates_presence_of :description, :message => 'Please Enter a Description'
    validates :description, length: {minimum: 10}

    validates_presence_of :prod_gender, :message => 'Please Enter a Category'
    validates :prod_gender, length: {minimum: 3}

    validates_presence_of :prod_price, :message => 'Please a Price'
    validates :prod_price, length: {minimum: 2}

    validates_presence_of :prod_size, :message => 'Please Enter a Brand'
    validates :prod_size, length: {minimum: 2}

    validates_presence_of :colours, :message => 'Please a Price'
    validates :colours, length: {minimum: 2}
    validates_presence_of :offer, :message => 'Please Enter a Brand'
    validates :offer, length: {minimum: 3}

    validates_presence_of :category, :message => 'Please Enter a Category'
    validates :category, length: {minimum: 3}

    validates_presence_of :brand, :message => 'Please Enter a Brand'
    validates :brand, length: {minimum: 3}

end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :customer
  belongs_to :address
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders


 # def username

  #  return self.email.split('@')[0].capitalize

 # end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @categories = Category.all
    @items = Item.all
  end

  def shoes
   @categories = Category.all
  # running = params[:cat_name]
  # @items = Item.where("category like ?", running)
  end

  def men
    @categories = Category.all
    #shoes = params[:cat_name]
    #@items = Item.where("item like ?", shoes)
  end

  def women
    @categories = Category.all
  end

  def kids
    @categories = Category.all
  end

  def category
    running = params[:cat_name]
    @items = Item.where("category like ?", running)
    #@products = Product.where(category_id: @category.id)
    #@products = Product.where("category like ?", running)
    #@items = Item.all
  end

  def search
     st = "%#{params[:q]}%"
     @items = Item.where("title like ?", st)
  end

  #def search
    #running = params[:title]
    #@items = Item.where("category like ?", running)
    #end
  #end

  #def categories
  #  @categories = Category.all
  #end

  def about
  end

  def contact
  end

  def shipment
  end

  #def support
    #session[:cart] = nil #a little hack to clear cart if you make error and it refuses to clear the session and clears the error in your code
  #end
  
  def myOrder
    @user= User.find(current_user.id)
    @orders = @user.orders.all
  end

  def returns
  end

  def payment
  end

  def giftcard
  end
#dealing with admin rules
  def admincontrol
    @users = User.all
    @orders = Order.all
  end

  def makeadmin
  @user = User.find_by(id: params[:id])
  @user.update_attribute(:admin, true)
  redirect_to "/"
  #redirect_to :controller => :"/"
  end

  def removeadmin
    @user = User.find_by(id: params[:id])
    @user.update_attribute(:admin, false)
    redirect_to "/"
    #redirect_to :controller => :"/"
  end

#Dealing with order payment
  def paid
    @order = Order.last
    #@order = Order.find(params[:id])
    #@order.update_attribute(:status, 'Order Paid')
    @order.update_attribute(:status, 'Paid with PayPal')
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/static_pages/admincontrol.html.erb
<% provide(:title, "Admin") %>

<%= link_to 'New Order', new_order_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button"  %>

<!--<p id="notice"><%#= notice %></p>-->

<div class="w3-container">
  <p id="notice"><%#= notice %></p>

  <% if current_user.admin? %> <!-- code for admin -->
  
    <!-- real admin following-->
    <% @users.each do |user| %>
    
    <p>User Id: <%= user.id %></p> <!-- number -->
    <p>First Name: <%= user.fname %></p> <!-- email -->
    <p>Is Admin?: <%= user.admin %></p> <!-- email -->
    <a href = "/makeadmin/<%= user.id %>" class="button">Make <%= user.email.split('@')[0].capitalize %> Admin</a> <!-- code for admin - button to allow the option -->
    <a href = "/removeadmin/<%= user.id %>" class="button">Remove <%= user.email.split('@')[0].capitalize %> Admin</a> <!-- make admin or remove from admin -->
    <% end %>
  
  <% end %>

</div>
  
  <div class="w3-container">
  <div class="w3-panel w3-pale-green w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black w3-animate-zoom">Orders</div>
  
    <div class="w3-panel">
      <table class="w3-table-all w3-card-4 w3-large">
         <% @orders.each do |order| %>
        <tr>
          <th>Order date</th>
          <th>User</th>
          <th>Status</th>
        </tr>
       
        <tr>
          <td><%= order.order_date %></td>
          <td><%= order.user %></td>
          <td><%= order.status %></td>
          <% if user_signed_in? %>
          <td><%= link_to 'Show', order, :class => "button", :role => "button" %></td>
          <td><%= link_to 'Edit', edit_order_path(order), :class => "button", :role => "button" %></td>
          <td><%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %></td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
<!--</div>-->

<!--<br>-->

<!--</div>-->

<!--<div>

<%#= link_to 'New Order', new_order_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button"  %>

  <h1>Orders</h1>

  <table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>User</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%# @orders.each do |order| %>
        <tr>
          <td><%#= order.order_date %></td>
          <td><%#= order.user %></td>
          <td><%#= order.status %></td>
          <td><%#= link_to 'Show', order %></td>
          <td><%#= link_to 'Edit', edit_order_path(order) %></td>
          <td><%#= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%# end %>
    </tbody>
  </table>

  <br>
</div>-->

app/views/static_pages/category.html.erb
<% provide(:title, "Category") %>

<% #if admin_signed_in? %>
<%= link_to 'New Item',  new_item_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button" %>
<% #end %>

<p id="notice"><%= notice %></p>

<!--items container-->
<!--<div id="itemsContainer">-->
<div class="w3-container">
  <!--<div class="w3-panel w3-lime w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Category</div>-->
  
  <% @items.each do |item| %>
  
  <!--<div class="">-->
  <div class="itemsIndex w3-container">
      <div class="w3-sand w3-padding-32 w3-half" style="height:400px">
        <div class="w3-margin-left w3-xlarge w3-right"> 
           <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
        </div>
      </div>
      <div class="w3-sand w3-padding-64 w3-half" style="height:400px">
        <h1><%= item.title %></h1>
        <div class="w3-margin-left"></div>
        <p><%= item.description %></p>
        <p>Price <%= number_to_currency(item.price, :unit => "€") %>
        <br>
        Category: <%= item.category %>
        <br>
        Brand: <%= item.brand %></p>
        
        <p>
          <!--<%# if user_signed_in? && current_user.admin? %>-->
          <% if user_signed_in? %>
          <%= link_to 'Show',  item, :class => "button", :role => "button" %>
          <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
          <%= link_to 'Delete',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
          <% end %>
          <a href="/cart/<%= item.id %>" class="button">Add to Cart</a>
        </p>
      </div>
    </div>
    
  <% end %>
  
  <% if @items.length == 0  %>
  <br>
  <h2>There are currently no products in this category</h2>
  <% end %>
  
  </div>
  
<br>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<!-- Image header -->
<div class="w3-container">
  <div class="w3-display-container">
      <%= image_tag("shoes2.jpg", alt: "Shoes", style: "width:100%")  %>
      <div class="w3-display-topleft w3-text-white" style="padding:30px 48px">
          <h1></h1>
      </div>
  </div>
</div>


<!--Recents Section-->
<div class="w3-container">
  <div class="w3-panel w3-green w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Popular Products</div>
  
  <%= render 'layouts/popular' %>
  
  </div>
</div>

<!--Categories Section-->
<div class="w3-container">
  <div class="w3-panel w3-orange w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Categories</div>

    <% @categories.each do |category| %>
    
    <div class="categories1 w3-panel w3-card-4 w3-sand">
      <a href="/category/<%= category.cat_name %>"> <img src="/assets/<%= category.image %>" alt="<%= category.cat_name %>" style= "width:100%"/> <h5><%= category.cat_name %></h5>
    </div>
    <% end %>
  </div>
    
    <!-- Category Section -->
      <!--<div class="w3-card-4 w3-teal w3-center w3-quarter w3-margin-left w3-margin-bottom" style="width:470px"> 
      <!--<div class="w3-card-4 w3-green w3-quarter w3-margin-right w3-center w3-margin-bottom" ><!--</div>style="width:27%">-->
          <%#= image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%") %>
          <%#= link_to (image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%")) %>
          <!--<a href="/category/<%#= category.cat_name %>"> <h5><%#= category.cat_name %></h5><!--<h1><%#= category.cat_title %></h1>-->
          <!--<p><%#= category.description %></p>-->
      <!--</div>  
    <%# end %>
</div>-->
  
  <!--<div class="w3-panel w3-card-4 w3-teal w3-center w3-padding w3-quarter w3-margin-left" style="width:275px">-->
  <!--<div class="w3-panel">
    <div class="categories1 w3-card-4 w3-teal w3-third">--> 
    <!--<div class="categories1 w3-card-4">-->
      <!--<div class="categories1 w3-container w3-border">-->
        <!--<div class="w3-display-container ">-->
        <!--<h1>Categories</h1>-->
        <%# @categories.each do |category| %>
    
        <!--<div class="w3-container">-->
        <!--<a href="/category/<%#= category.cat_name %>"> <img src="/assets/<%#= category.image %>" alt="<%#= category.cat_name %>" style= "width:100%" /> <h1><%#= category.cat_name %></h1>-->
        <!--<a href="/category/<%#= category.cat_name %>"> <img src="/assets/<%#= category.image %>" alt="<%#= category.cat_name %>" style= "width:100%"/> <h5><%#= category.cat_name %></h5>-->

        <!--<a href="/category/<%#= category.title %>">-->
        <!--<img src="/assets/<%# category.image %>" alt="<%# category.cat_name %>"/>-->
        <!--<p><%#= category.description %></p>-->
         <%#= image_tag("shoes2.jpg", alt: "Shoes", style: "width:100%")  %>
        <!--</div>-->
        <%# end %>
        <!--</div>-->
    <!--</div>
    <%# end %>
  </div>-->
  

<!--<a href="/category/<%#= category.title %>"> <img src="/assets/<%#= category.image %>" alt="<%#= category.title %>" /> </a>-->

<!-- Card Image Section -->
<!--<div class="w3-panel">
  <div class="w3-row-padding w3-margin-top">
    <div class="w3-third">
      <div class="w3-card w3-hover-opacity">
        <%#= link_to (image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%")), items_url %>
        <%#= link_to (image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%")), men_url %>
        <div class="w3-container w3-center">
          <h5>Mens Shoes</h5>
        </div>
      </div>
    </div>

    <div class="w3-third">
      <div class="w3-card w3-hover-opacity">
        <%#= link_to (image_tag("womShoe.jpg", alt: "Womens Shoe", style: "width:100%")), items_url %>
        <%#= link_to (image_tag("womShoe.jpg", alt: "Mens Shoe", style: "width:100%")), women_url %>
        <div class="w3-container w3-center">
          <h5>Womens Shoes</h5>
        </div>
      </div>
    </div>

    <div class="w3-third">
      <div class="w3-card w3-hover-opacity">
        <%#= link_to (image_tag("kidShoe.jpg", alt: "Kids Shoe", style: "width:100%")), items_url %>
        <%#= link_to (image_tag("kidShoe.jpg", alt: "Mens Shoe", style: "width:100%")), kids_url %>
        <div class="w3-container w3-center">
          <h5>Kids Shoes</h5>
        </div>
      </div>
    </div>
  </div>
</div>

<br>-->

app/views/static_pages/kids.html.erb
<div class="w3-container">
  <div class="w3-panel w3-green w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Kids Categories</div>

    <% @categories.each do |category| %>
    
    <!-- Category Section -->
    <!--<div class="kidsCat">-->
      <div class="w3-card-4 w3-green w3-quarter w3-margin-left w3-center w3-margin-bottom" style="width:353px" >
      <%= image_tag("kidShoe.jpg", alt: "Kids Shoe", style: "width:100%") %>
      <a href="/category/<%= category.cat_name %>"> <h5><%= category.cat_name %></h5><!--<h1><%#= category.cat_title %></h1>-->
       <!--<p><%#= category.description %></p>-->     
      </div>  
    <!--</div>-->
      
    <% end %>
</div>

app/views/static_pages/men.html.erb
<% provide(:title, "Men") %>

<div class="w3-container">
  <div class="w3-panel w3-blue w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Mens Shoes</div>

    <% @categories.each do |category| %>
    
    <%# @items.each do |item| %>
    
    <!-- Category Section -->
    <!--<div class="menCat">-->
      <div class="w3-card-4 w3-blue w3-quarter w3-margin-left w3-center w3-margin-bottom" style="width:353px" >
          <%= image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%") %>
          <!--<img src="/assets/<%# category.image %>" alt="<%# category.cat_name %>" />-->
          <a href="/category/<%= category.cat_name %>"> <h5><%= category.cat_name %></h5><!--<h1><%#= category.cat_title %></h1>-->
          <p><%= category.description %></p>
      </div>  
    <!--</div>-->

    <% end %>
</div>

app/views/static_pages/offers.html.erb
<% provide(:title, "Offers") %>

app/views/static_pages/paid.html.erb
<!--<h1>Thanks for your payment!!</h1>-->

<!-- Thanks you Section -->
<div class="w3-panel">
  <div class="w3-third w3-container w3-white">
  </div>

  <div class="w3-third w3-card-4 w3-teal w3-text-white w3-center" > <!--style="height:300px;" >-->
      <h1>Thanks for your payment!!</h1>
      <h2>Your order will be shipped ASAP</h2>

      <!--<p><a href="/items" class="w3-button w3-deep-orange w3-hover-sand">Continue Shopping</a></p>-->
      <p><a href="/clearcart" class="w3-button w3-deep-orange w3-hover-sand">Continue Shopping</a></p>
      <!--<p><a href="/clearcart" class="w3-button w3-deep-orange w3-hover-sand">Back To Cart</a></p>
      <a href='/paid/<%#= order.id %>' class="button">Pay Now</a><a href="/items" class="button">Continue Shopping</a>-->
  </div>
</div>

app/views/static_pages/payment.html.erb
<% provide(:title, "Payment") %>

app/views/static_pages/returns.html.erb
<% provide(:title, "Returns") %>

<h1 class="w3-center">Shipping and Returns Policy</h1>

<div class="w3-container">


<p class="w3-center">Here at Shoes@Web we aim for all customers to be completely satisfied with the products purchased from us. If this is not the case, please get in touch with us. We take great care in ensuring that on our website each product is presented in its true representation.
We use An Post and International Couriers to ship around the world.</p>

<p class="w3-center"><strong>Shipping</strong></br>
</br>
<i class="w3-center">Ireland and Northern Ireland</i></br>
Free deliveries on orders over €50. Orders under the value of €50 will incur a standard delivery charge of €5.00. Orders are processed Monday to Friday and you will receive your order within 1-2 working days.
Orders placed on the weekend will be dispatched first thing Monday. During peak times deliveries may take slightly longer than expected. In the event that the delivery address is unoccupied, couriers will generally call back later the same day or on the following day. For this reason, a business address is always preferable as a delivery address. A phone number for the delivery address/recipient is always necessary in the event that the courier needs to make contact.</br>
<i class="w3-center">UK</i></br>
Delivery is free to the UK on orders over €99. Orders under that value will incur a standard delivery charge of €9.95 for 10kg. Deliveries take 2-3 working days.
Europe and Rest of World Shipping rates for 10kg are as follows:
€9.95 to: Belgium – France – Germany – Luxembourg – Netherlands – Austria – Denmark – Switzerland – Finland
€13.95 to: Czech Republic – Hungary – Italy – Poland – Sweden – Slovenia – Slovakia
€19.95 to: Spain Mainland – Norway – Portugal
€22.95 to: Bulgaria – Estonia – Lithuania – Latvia – Romania – Spain
An Post operates a ship by weight facility for deliveries to all other destinations.</p>
<p class="w3-center"><strong>Returns</strong> </br>
Please make sure to check your delivery once it arrives as any shortages must be notified on receipt of your parcel. Our Policy on returns and exchanges is that all of our product (apart from the non-refundable items listed below) can be returned for an exchange or refund within 28 days of receipt. To be eligible for a return:</br>
•	Items must be unused.</br>
•	Items must be in the same condition in which they were received.</br>
•	Items must be in their original packaging.</br>
•	We will accept cancellations on our products at any time prior to dispatch.</br></p>
<p class="w3-center"><strong>Non Refundable Products</strong> </br>
•	Items which have been damaged</br>
•	Parts of a product which have been lost after receipt</br></p>
<p class="w3-center"><strong>Refunds</strong> </br>
Refunds will be given in accordance with the method of payment. Please note we do not pay for cost of returns under this guarantee.</p>
<p class="w3-center"><strong>Late or Missing Refunds</strong> </br>
There is often some processing time before a refund is completed but please contact us at info@shoes@web.ie if a refund has not been credited within 10 days of confirmation from us.</p>
<p class="w3-center"><strong>Sales items </strong></br>
Only regular priced items may be refunded, unfortunately, items that are on sale cannot be refunded.</p>
<p class="w3-center"><strong>Damaged Goods</strong> </br>
If items are damaged during transit, then we will replace them free of charge once the original product has been returned to us. In order for the event of this occurring, you will also receive a full refund on any postage costs you incurred for the return of same.</p>
<p class="w3-center"><strong>Shipping</strong> </br>
Please pack products up as they were delivered and return them to: Shoes@Web, 42 Main Street, Dublin, Ireland.</br>
Please note – We can’t guarantee that we will receive your returned item. Therefore, you should consider either using a trackable shipping service or purchasing shipping insurance.
</p>
</div>

app/views/static_pages/search.html.erb
<% provide(:title, "Search") %>

<div class="w3-container">
    
    <h2>You Searched Our Product Catalog For <%= @search_term %></h2>
    
    <% if @items.length == 0  %>
    <br />
    <h2>No products were found to match your search</h2>
    <% end %>
    
    
    <table class="catalog">
      <% @items.each do |item| %>
          <tr>
            <td>
              <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
              </div>
              <div class="title">
                <%= link_to item.title, item %>
              </div>
              <div class="description">
                <%= item.description %>
              </div>  
              <div class="price">
                 <%= number_to_currency(item.price, :unit => "€") %>
              </div>
              <div class="links">
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_item_path(item), :class => "button", :role => "button" %>
                  <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
                <%else%>
                
                  <a href="/cart/<%= item.id %>" class="button">Add to Cart</a>
                <%end%>  
            </div>
            </td>
          </tr>
        <% end %>
    </table>

</div>

app/views/static_pages/shipment.html.erb
<% provide(:title, "Shipment") %>

app/views/static_pages/shoes.html.erb
<div class="w3-container">
  <div class="w3-panel w3-orange w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Categories</div>

    <% @categories.each do |category| %>
    
    <!-- Category Section -->
    <div class="w3-panel w3-card-4 w3-teal w3-center w3-padding w3-quarter w3-margin-left" style="width:275px">
      <a href="/category/<%= category.cat_name %>"> <img src="/assets/<%= category.image %>" alt="<%= category.cat_name %>" style= "width:100%"/> <h5><%= category.cat_name %></h5>
    </div>  
    
    <% end %>
</div>


      <!--<div class="w3-panel w3-card-4 w3-teal w3-center w3-padding w3-quarter w3-margin-left" style="width:275px">-->
      <!--<div class="w3-card-4 w3-green w3-quarter w3-margin-right w3-center w3-margin-bottom"> <!--style="width:20%">-->
          <%#= link_to (image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%")) %>
          <%#= image_tag("menShoe.jpg", alt: "Mens Shoe", style: "width:100%") %>
          <!--<a href="/category/<%#= category.cat_name %>"> <img src="/assets/<%#= category.image %>" alt="<%#= category.cat_name %>" style= "width:100%"/> <h5><%#= category.cat_name %></h5>-->
          <!--<p><%#= category.description %></p>-->
      <!--</div>  
    
    <%# end %>
</div>-->

app/views/static_pages/support.html.erb
<% provide(:title, "Support") %>

app/views/static_pages/women.html.erb
<div class="w3-container">
  <div class="w3-panel w3-pink w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Womens Categories</div>

    <% @categories.each do |category| %>
    
    <!-- Category Section -->
    <!--<div class="womenCat">-->
      <div class="w3-card-4 w3-pink w3-quarter w3-margin-left w3-center w3-margin-bottom" style="width:353px" >
      <%= image_tag("womShoe.jpg", alt: "Womens Shoe", style: "width:100%") %>
      <a href="/category/<%= category.cat_name %>"> <h5><%= category.cat_name %></h5><!--<h1><%#= category.cat_title %></h1>-->
      </div>  
    <!--</div>-->
      
    <% end %>
</div>