config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :shippings
  resources :payments
  resources :products
  resources :offers
  resources :brands
  resources :categories
  resources :addresses
  resources :admins
  resources :customers
  resources :orders do
  resources:orderitems
  end

  #resources :orders


  #security measures for app - permissions for different users
  devise_for :admin do
    resources:orders.all
  end

  #admin rule
  get '/makeadmin/:id' => 'static_pages#makeadmin'
  get '/removeadmin/:id' => 'static_pages#removeadmin'

  devise_for :users do
    resources:orders
  end

  #get '/login' => 'user#login'
  #get '/logout' => 'user#logout'
  #get '/register' => 'user#register'

  root 'static_pages#home'

  get '/items' => 'items#index'
  get '/products' => 'products#index'

  #cart section
  get '/checkout' => 'cart#createOrder'
  get 'cart/index'
  get '/cart' => 'cart#index'
  #get 'cart/index'
  get '/cart/:id' => 'cart#add'
  get '/clearcart' => 'cart#clearcart'
  get '/remove/:id' => 'cart#remove'
  get '/decrease/:id' => 'cart#decrease'
  get '/increase/:id' => 'cart#increase'
  get '/paid/:id' => 'static_pages#paid'
  get '/done' => 'cart#done'

  get '/admin' => 'static_pages#admincontrol'

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/shippings' => 'static_pages#shippings'
  get '/support' => 'static_pages#support'
  get '/returns' => 'static_pages#returns'
  get '/offers' => 'static_pages#offers'
  get '/payments' => 'static_pages#payments'
  get '/brands' => 'static_pages#brands'
  get '/addresses' => 'static_pages#addresses'
  get '/customers' => 'static_pages#customers'

  get '/men' => 'static_pages#men'
  #get '/item/:title' => 'static_pages#items'

  get '/women' => 'static_pages#women'

  get '/kids' => 'static_pages#kids'

  #get '/search' => 'search_pages#search'
  #get '/categories' => 'static_pages#categories'
  #get '/category/:title' => 'static_pages#category'

  get '/category' => 'static_pages#category'
  get '/category/:cat_name' => 'static_pages#category'

  post '/search' => 'items#search'
  get '/search' => 'static_pages#search'
  get '/search/:title' => 'static_pages#search'

  get '/shoes' => 'static_pages#shoes'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :payment
  belongs_to :shipping
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord

    validates_presence_of :title, :message => 'Please Enter a Title'
    validates :title, length: {minimum: 5}

    validates_presence_of :description, :message => 'Please Enter a Description'
    validates :description, length: {minimum: 10}

    validates_presence_of :price, :message => 'Please a Price'
    validates :price, length: {minimum: 2}

    validates_presence_of :category, :message => 'Please Enter a Category'
    validates :category, length: {minimum: 3}

    validates_presence_of :brand, :message => 'Please Enter a Brand'
    validates :brand, length: {minimum: 3}

end

# :price, :image_url, :category, :brand

app/models/offer.rb
class Offer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitems
  belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :shipping
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord


    validates_presence_of :prod_name, :message => 'Please Enter a product name'
    validates :prod_name, length: {minimum: 5}

    validates_presence_of :description, :message => 'Please Enter a Description'
    validates :description, length: {minimum: 10}

    validates_presence_of :prod_gender, :message => 'Please Enter a Category'
    validates :prod_gender, length: {minimum: 3}

    validates_presence_of :prod_price, :message => 'Please a Price'
    validates :prod_price, length: {minimum: 2}

    validates_presence_of :prod_size, :message => 'Please Enter a Brand'
    validates :prod_size, length: {minimum: 2}

    validates_presence_of :colours, :message => 'Please a Price'
    validates :colours, length: {minimum: 2}
    validates_presence_of :offer, :message => 'Please Enter a Brand'
    validates :offer, length: {minimum: 3}

    validates_presence_of :category, :message => 'Please Enter a Category'
    validates :category, length: {minimum: 3}

    validates_presence_of :brand, :message => 'Please Enter a Brand'
    validates :brand, length: {minimum: 3}

end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :customer
  belongs_to :address
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders


 # def username

  #  return self.email.split('@')[0].capitalize

 # end



end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admins/_form.html.erb
<div class='admins'>
  
  <div class="w3-card-4">
    <div class="w3-container w3-green w3-text-white w3-center">
      <h2>New Admin</h2>
    </div>
    
    <br>
    
    <div class="w3-container w3-text-grey">

      <%= form_for(admin) do |f| %>
        <% if admin.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>
      
            <ul>
            <% admin.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="field">
          <%= f.label :first %>
          <%= f.text_field :fname %>
        </div>
      
        <div class="field">
          <%= f.label :last %>
          <%= f.text_field :lname %>
        </div>
      
        <div class="field">
          <%= f.label :phone %>
          <%= f.text_field :phonenumber %>
        </div>
      
        <div class="field">
          <%= f.label :dob %>
          <%= f.date_select :date_of_birth %>
        </div>
      
        <div class="field">
          <%= f.label :user_id %>
          <%= f.text_field :user_id %>
        </div>
      
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

app/views/admins/edit.html.erb
<!--<h1>Editing Admin</h1>

<%#= render 'form', admin: @admin %>

<%#= link_to 'Show', @admin %> |
<%#= link_to 'Back', admins_path %>-->

<div class="w3-container">
    <h1>Editing Admin</h1>
    <%= link_to 'Show', @admin, :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %> 
    <%= link_to 'Back', admins_path, :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %>
    <%= render 'form', admin: @admin %>
</div>

app/views/admins/index.html.erb
<% provide(:title, "Admins") %>

<% #if admin_signed_in? %>
<%= link_to 'New Admin',  new_admin_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button" %>
<% #end %>

<p id="notice"><%= notice %></p>

<div class="w3-container">
  <div class="w3-panel w3-green w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Admins</div>
  <% @admins.each do |admin| %>
  
  <div class="admins w3-container">
      <div class="w3-sand w3-padding-32 w3-half" style="height:500px">
        
      </div>
  
    <div class="w3-sand w3-padding-64 w3-half" style="height:500px">
      <h1><%= admin.fname %></h1>
      <div class="w3-margin-left"></div>
      <p><%= admin.lname %></p>
      <p><%= admin.phonenumber %></p>
      <p><%= admin.date_of_birth %></p>
      <p><%= admin.user %></p>
      <p>
        <% if user_signed_in? %>
        <%= link_to 'Show', admin, :class => "button", :role => "button" %>
        <%= link_to 'Edit', edit_admin_path(admin), :class => "button", :role => "button" %>
        <%= link_to 'Delete', admin, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
        <% end %>
      </p>
    </div>
  </div>
    
  <% end %>
  
</div>
  
<br>

<!--<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Phonenumber</th>
      <th>Date of birth</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @admins.each do |admin| %>
      <tr>
        <td><%#= admin.fname %></td>
        <td><%#= admin.lname %></td>
        <td><%#= admin.phonenumber %></td>
        <td><%#= admin.date_of_birth %></td>
        <td><%#= admin.user %></td>
        <td><#= link_to 'Show', admin %></td>
        <td><%#= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%#= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>-->

<!--<%#= link_to 'New Admin', new_admin_path %>-->

app/views/admins/new.html.erb
<!--<h1>New Admin</h1>-->

<%= link_to 'Back', admins_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button" %>

<%= render 'form', admin: @admin %>

app/views/admins/show.html.erb
<div class="adminSuccess">
   <div class="w3-card-4">
      <div class="w3-container w3-deep-orange w3-text-white w3-center w3-wide">
        <h2>Admin Details</h2>
      </div>
      
      <p id="notice"><%= notice %></p>
      
      <div class="w3-center w3-wide">
        <p>
          <strong>First:</strong>
          <%= @admin.fname %>
        </p>
        
        <p>
          <strong>Last:</strong>
          <%= @admin.lname %>
        </p>
        
        <p>
          <strong>Phone:</strong>
          <%= @admin.phonenumber %>
        </p>
        
        <p>
          <strong>DOB:</strong>
          <%= @admin.date_of_birth %>
        </p>
        
        <p>
          <strong>User:</strong>
          <%= @admin.user %>
        </p>
        
        <div class="w3-panel w3-pale-green w3-padding-24">
          <%= link_to 'Edit', edit_admin_path(@admin), :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %> 
          <%= link_to 'Back', admins_path, :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %>
        </div>
      </div>
    </div>
</div>