config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :shippings
  resources :payments
  resources :products
  resources :offers
  resources :brands
  resources :categories
  resources :addresses
  resources :admins
  resources :customers
  resources :orders do
  resources:orderitems
  end

  #resources :orders


  #security measures for app - permissions for different users
  devise_for :admin do
    resources:orders.all
  end

  #admin rule
  get '/makeadmin/:id' => 'static_pages#makeadmin'
  get '/removeadmin/:id' => 'static_pages#removeadmin'

  devise_for :users do
    resources:orders
  end

  #get '/login' => 'user#login'
  #get '/logout' => 'user#logout'
  #get '/register' => 'user#register'

  root 'static_pages#home'

  get '/items' => 'items#index'
  get '/products' => 'products#index'

  #cart section
  get '/checkout' => 'cart#createOrder'
  get 'cart/index'
  get '/cart' => 'cart#index'
  #get 'cart/index'
  get '/cart/:id' => 'cart#add'
  get '/clearcart' => 'cart#clearcart'
  get '/remove/:id' => 'cart#remove'
  get '/decrease/:id' => 'cart#decrease'
  get '/increase/:id' => 'cart#increase'
  get '/paid/:id' => 'static_pages#paid'
  get '/done' => 'cart#done'

  get '/admin' => 'static_pages#admincontrol'

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/shippings' => 'static_pages#shippings'
  get '/support' => 'static_pages#support'
  get '/returns' => 'static_pages#returns'
  get '/offers' => 'static_pages#offers'
  get '/payments' => 'static_pages#payments'
  get '/brands' => 'static_pages#brands'
  get '/addresses' => 'static_pages#addresses'
  get '/customers' => 'static_pages#customers'

  get '/men' => 'static_pages#men'
  #get '/item/:title' => 'static_pages#items'

  get '/women' => 'static_pages#women'

  get '/kids' => 'static_pages#kids'

  #get '/search' => 'search_pages#search'
  #get '/categories' => 'static_pages#categories'
  #get '/category/:title' => 'static_pages#category'

  get '/category' => 'static_pages#category'
  get '/category/:cat_name' => 'static_pages#category'

  post '/search' => 'items#search'
  get '/search' => 'static_pages#search'
  get '/search/:title' => 'static_pages#search'

  get '/shoes' => 'static_pages#shoes'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :payment
  belongs_to :shipping
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord

    validates_presence_of :title, :message => 'Please Enter a Title'
    validates :title, length: {minimum: 5}

    validates_presence_of :description, :message => 'Please Enter a Description'
    validates :description, length: {minimum: 10}

    validates_presence_of :price, :message => 'Please a Price'
    validates :price, length: {minimum: 2}

    validates_presence_of :category, :message => 'Please Enter a Category'
    validates :category, length: {minimum: 3}

    validates_presence_of :brand, :message => 'Please Enter a Brand'
    validates :brand, length: {minimum: 3}

end

# :price, :image_url, :category, :brand

app/models/offer.rb
class Offer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitems
  belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :shipping
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord


    validates_presence_of :prod_name, :message => 'Please Enter a product name'
    validates :prod_name, length: {minimum: 5}

    validates_presence_of :description, :message => 'Please Enter a Description'
    validates :description, length: {minimum: 10}

    validates_presence_of :prod_gender, :message => 'Please Enter a Category'
    validates :prod_gender, length: {minimum: 3}

    validates_presence_of :prod_price, :message => 'Please a Price'
    validates :prod_price, length: {minimum: 2}

    validates_presence_of :prod_size, :message => 'Please Enter a Brand'
    validates :prod_size, length: {minimum: 2}

    validates_presence_of :colours, :message => 'Please a Price'
    validates :colours, length: {minimum: 2}
    validates_presence_of :offer, :message => 'Please Enter a Brand'
    validates :offer, length: {minimum: 3}

    validates_presence_of :category, :message => 'Please Enter a Category'
    validates :category, length: {minimum: 3}

    validates_presence_of :brand, :message => 'Please Enter a Brand'
    validates :brand, length: {minimum: 3}

end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :customer
  belongs_to :address
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders


 # def username

  #  return self.email.split('@')[0].capitalize

 # end



end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:brand_name, :description, :yearofestablishement)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/brands/_form.html.erb
<div class='brands'>
  
  <div class="w3-card-4">
    <div class="w3-container w3-green w3-text-white w3-center">
      <h2>New Brand</h2>
    </div>
    
    <br>
    
    <div class="w3-container w3-text-grey">
  
      <%= form_for(brand) do |f| %>
        <% if brand.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>
      
            <ul>
            <% brand.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="field">
          <%= f.label :brand_name %>
          <%= f.text_field :brand_name %>
        </div>
      
        <div class="field">
          <%= f.label :description %>
          <%= f.text_field :description %>
        </div>
      
        <div class="field">
          <%= f.label :established %>
          <%= f.date_select :yearofestablishement %>
        </div>
      
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

app/views/brands/edit.html.erb
<div class="w3-container">
    <h1>Editing Brand</h1>
    <%= link_to 'Show', @brand, :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %> 
    <%= link_to 'Back', brands_path, :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %>
    <%= render 'form', brand: @brand %>
</div>

app/views/brands/index.html.erb
<% provide(:title, "Brands") %>

<% #if admin_signed_in? %>
<%= link_to 'New Brand',  new_brand_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button" %>
<% #end %>

<p id="notice"><%= notice %></p>

<!--<h1>Brands</h1>-->

<div class="w3-container">
  <div class="w3-panel w3-green w3-jumbo w3-center w3-topbar w3-bottombar w3-border-black">Brands</div>
  <% @brands.each do |brand| %>
  
  <div class="brands w3-container">
      <div class="w3-sand w3-padding-32 w3-half" style="height:400px">
        
      </div>
  
    <div class="w3-sand w3-padding-64 w3-half" style="height:400px">
      <h1><%= brand.brand_name %></h1>
      <div class="w3-margin-left"></div>
      <p><%= brand.description %></p>
      <p><%= brand.yearofestablishement %></p>
      <p>
        <% if user_signed_in? %>
        <%= link_to 'Show', brand, :class => "button", :role => "button" %>
        <%= link_to 'Edit', edit_brand_path(brand), :class => "button", :role => "button" %>
        <%= link_to 'Delete', brand, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
        <% end %>
      </p>
    </div>
  </div>
    
  <% end %>
  
</div>
  
<br>
  

<!--<table>
  <thead>
    <tr>
      <th>Brand name</th>
      <th>Description</th>
      <th>Yearofestablishement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.brand_name %></td>
        <td><%= brand.description %></td>
        <td><%= brand.yearofestablishement %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>-->

app/views/brands/new.html.erb
<!--<h1>New Brand</h1>-->

<%= link_to 'Back', brands_path, :class => "w3-button w3-orange w3-hover-green w3-round-xxlarge w3-margin-left", :role => "button" %>

<%= render 'form', brand: @brand %>

app/views/brands/show.html.erb
<div class="brandSuccess">
   <div class="w3-card-4">
      <div class="w3-container w3-deep-orange w3-text-white w3-center w3-wide">
        <h2>Brand Details</h2>
      </div>

      <p id="notice"><%= notice %></p>
      
    <div class="w3-center w3-wide">
      <p> 
        <strong>Brand name:</strong>
        <%= @brand.brand_name %>
      </p>
      
      <p>
        <strong>Description:</strong>
        <%= @brand.description %>
      </p>
      
      <p>
        <!--<strong>Yearofestablishement:</strong>-->
        <strong>Established:</strong>
        <%= @brand.yearofestablishement %>
      </p>
      
      <div class="w3-panel w3-pale-green w3-padding-24">
        <%= link_to 'Edit', edit_brand_path(@brand), :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %> 
        <%= link_to 'Back', brands_path, :class => "w3-button w3-orange w3-hover-green w3-round-large w3-margin-left", :role => "button" %>
      </div>
      
    </div>  
      
    </div>
  </div>